### ISSUE TITLE
FAILED Error: spawn EACCES

### ISSUE THREAD

**Issue by nickzuber** [dcodeIO/webassembly#13]
When I follow the steps for running the example here, I run into an error regarding access rights. Is there some more set up that isn't mentioned here that I could be missing?

I'm running node `v6.11.1`

I get the same error if I use `sudo` as well.

```
❯ wa compile -o program.wasm program.c
Compiling on darwin-x64 ...

clang program.c
 -c
 --target=wasm32-unknown-unknown
 -emit-llvm
 -nostdinc
 -nostdlib
 -D WEBASSEMBLY
 -isystem /Users/nick/.nvm/versions/node/v5.12.0/lib/node_modules/webassembly/include
 -o /var/folders/4f/gjs6r6bj2xqcx4dmh91_njl00000gn/T/wa1_216779hYBi2Zw1d18.tmp

FAILED Error: spawn EACCES
    at exports._errnoException (util.js:893:11)
    at ChildProcess.spawn (internal/child_process.js:302:11)
    at Object.exports.spawn (child_process.js:367:9)
    at /Users/nick/.nvm/versions/node/v5.12.0/lib/node_modules/webassembly/cli/util.js:33:34
    at Object.run (/Users/nick/.nvm/versions/node/v5.12.0/lib/node_modules/webassembly/cli/util.js:32:12)
    at Object.exports.main.defines.forEach.headers.forEach.include.forEach [as main] (/Users/nick/.nvm/versions/node/v5.12.0/lib/node_
modules/webassembly/cli/compiler.js:108:10)
    at Object.<anonymous> (/Users/nick/.nvm/versions/node/v5.12.0/lib/node_modules/webassembly/bin/wa-compile:2:38)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
```

**Comment by victorperin** [comment]
Same error here

**Comment by devsnek** [comment]
@dcodeIO any word on this? i also am getting this error.

EDIT: i'm a cuck and didn't fully read this issue before saying i was having it, i'll throw open a new one

**Comment by dcodeIO** [comment]
The bin-files live in tools/bin/ARCH, you could try to change their access permissions
